rabbitmq:
  queue:
    name: invest_queue
  exchange:
    name: invest_exchange
  routing:
    key: invest_routing_key
  application:
    name: producer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/producer?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: false
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin