spring:
  application:
    name: producer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: false
    open-in-view: false
